// import './form';
import './datapicker.min';
import  './jquery.maskedinput.min';
import './jquery-ui.min.js';
// import './includes/like_btn';
// import './includes/checkbox';
// import './includes/clickme_all';
// import './includes/clickme_border';
// import './includes/clickme_text';
// import './includes/input';
// import './includes/slider';
// import './includes/dropdown_guests';
// import './includes/dropdowm_room';
// import './includes/radio_btn';
// import './includes/toggle';
// import './card';
// import './includes/rate_btn';
import './includes/pagination';
// import './calendar';