// import './form';
import './datapicker.min';
import  './jquery.maskedinput.min';
import './jquery-ui.min.js';
import './includes/checkbox';
// import './includes/button';
import './includes/input';
import './includes/slider';
import './includes/dropdown';
// import './includes/radio_btn';
// import './includes/toggle';
// import './includes/like_btn';
import './card';
import './includes/rate_btn';
// import './includes/pagination';
// import './calendar';